apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: dep1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dep1
  template:
    metadata:
      labels:
        app: dep1
    spec:
      containers:
      - name: pod1
        image: redis:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: lbservice
spec:
 selector:
  app: dep1
 ports:
  - port: 8082
 type: LoadBalancer

