
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: demoforgitops
  labels:
    app: dep1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dep1
  template:
    metadata:
      labels:
        app: dep1
    spec:
      containers:
       - name: aks-helloworld
        image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: "Welcome to Azure Kubernetes Service (AKS)"
    
---
apiVersion: v1
kind: Service
metadata:
 name: lbservice
 namespace: demoforgitops
spec:
 selector:
  app: dep1
 ports:
  - port: 8082
    targetPort: 80
 type: LoadBalancer


